### ISSUE TITLE
TEX - No focus bypass after McMath inauguration

### ISSUE THREAD

**Issue by AustinIGuess** [kalterkrieg/Kalterkrieg-bug-reports#149] opened 2024-07-05 22:36 UTC
### OS

Windows

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1

### List any other mods used

Player-Led Peace Confrences

### Were you using Steam?

Yes

### Were you in multiplayer?

Yes

### Which expansions do you NOT have?

None

### Explanation of the Issue

Following the Primary Elections and AFP Convention, McMath was choosen and the inauguration countdown began. However, following the end of the event, McMath's focus path never unlocked

### Save File

@
[TEX_1949_03_09_08.zip](https://github.com/user-attachments/files/16114158/TEX_1949_03_09_08.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment] 2024-07-07 00:10
Hi, trying to follow up on this but cannot reproduce. Did you get the event that McMath was inaugurated?

**Comment by thelilh** [comment] 2024-07-07 14:49
Would need the game.log and error.log to fix this. it should be very rare for it to happen.

**Comment by AustinIGuess** [comment] 2024-07-07 15:10
Disregard, I figured out that I had just dismissed a few of the events for the convention so no candidate received a majority, sorry for the confusion.

**Comment by thelilh** [comment] 2024-07-07 16:27
oh, is that what happened? good to know. I'll fix it

**Comment by thelilh** [comment] 2024-07-12 12:13
This is now fixed

**Closed by thelilh** 2024-07-12 12:12 UTC
Labels: Bug
