### ISSUE TITLE
GER - The Ruckkehrprogramm Complete event uses the generic picture

### ISSUE THREAD

**Issue by Ikidikid** [kalterkrieg/Kalterkrieg-bug-reports#294] opened 2024-07-25 14:04 UTC
### OS

Windows 10

### HOI4 Version

1.14.7

### Kalterkrieg Version

0.1.2

### List any other mods used

Kalterkrieg Models and All Kaiserreich Models

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

No, I have all

### Screenshots

![Image_1](https://github.com/user-attachments/assets/016593cb-cedd-4a93-90a9-3aa14d50cc30)

### Save File

[GER_game.zip](https://github.com/user-attachments/files/16378740/GER_game.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by thelilh** [comment] 2024-07-25 14:18
Not a bug, just missing GFX

**Comment by thelilh** [comment] 2024-07-25 14:20
Will be fixed in next patch

**Closed as completed by thelilh** 2024-07-25 14:20 UTC
Labels: GFX
