### ISSUE TITLE
NEE- Dewey wont lose 

### ISSUE THREAD

**Issue by SuchAFoolForYou** [kalterkrieg/Kalterkrieg-bug-reports#330] opened 2024-08-02 18:22 UTC
### OS

Windows 10

### HOI4 Version

v1.14.7.f4d3(f03b)

### Kalterkrieg Version

Updated Aug 1 @ 9:35pm edt

### List any other mods used

Precise Buffs - Cheat Ideas, Toolpack without the Errors 

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

n/a

### Explanation of the Issue

Dewey won the 53 elections when he shouldnt have. Harriman carried more states. The electoral total is also more than it should be if you add up the votes of all the states in the states gui. The total electoral vote count should be 135. the event total is 270.

### Screenshots

![hoi4_49](https://github.com/user-attachments/assets/831f7529-708e-47c4-9433-543d08765895)

### Save File

https://1drv.ms/u/s!AjdelN0xrk1xg8gk8_ehcgWjnLF1rQ?e=cbehy2

### Log Files

https://1drv.ms/u/s!AjdelN0xrk1x9wMwO-N18zUnNbsd?e=ZBIFOm

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Kennedy2523** [comment] 2024-08-05 01:16
Through testing, believe this was fixed with the stealth fix as we cannot reproduce. If you encounter it again, please report.

**Closed as completed by Kennedy2523** 2024-08-05 01:16 UTC
Labels: Bug
